# syntax=docker/dockerfile:experimental
FROM {{cookiecutter.project_slug}}-image-base

USER root
RUN apt-get update
# Needed for drizly_dagster_utils install
RUN apt-get install openssh-client git -y
RUN apt-get install build-essential -y
RUN apt-get install -yqq cron

#This exists in order to do a pip install of drizly_dagster_utils wherever needed
RUN mkdir -p -m 0700 ~/.ssh
RUN ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh,mode=0666  pip install git+ssh://git@github.com/DrizlyInc/drizly-dagster.git@ds_js/margin-optimized-sort-skeleton"#egg=integrations&subdirectory=drizly_dagster_utils"

USER docker

COPY ./dev_requirements.txt /dev_requirements.txt
RUN pip install --use-feature=2020-resolver -r  /dev_requirements.txt


WORKDIR /work

ENTRYPOINT ["/bin/bash"]
