resources:
  snowflake:
    config:
      secret_name: snowflake/analytics_api
      region: us-east-1
  redis:
    config:
      host: development-recs-redis.dgvvsn.0001.use1.cache.amazonaws.com
      port: 6379
      db: "0"
solids:
  get_because_you_bought_df:
    inputs:
      query:
        value: SELECT * FROM STAGE_JS.DATASCIENCE.{{cookiecutter.project_slug}} LIMIT 10