resources:
  snowflake:
    config:
      secret_name: snowflake/analytics_api
      region_name: us-east-1
  s3:
    config:
      bucket: drizly-ml
    {{cookiecutter.project_slug}}:
      key_path: dev/{{cookiecutter.project_slug}}/
model:
  train_output: /opt/ml/model
  model_name: {{cookiecutter.project_slug}}Model.pkl

