resources:
  snowflake:
    config:
      secret_name: snowflake/analytics_api
      region: us-east-1
  redis:
    config:
      host: localhost
      port: 6379
      db: "0"
solids:
  get_because_you_bought_df:
    inputs:
      query:
        value: SELECT * FROM STAGE_JS.DATASCIENCE.RECS_BECAUSE_YOU_BOUGHT LIMIT 100000