resources:
  snowflake:
    config:
      secret_name: snowflake/analytics_api
      region: us-east-1
  redis:
    config:
      host: localhost
      port: 6379
      db: "0"
solids:
  get_{{cookiecutter.project_slug}}_df:
    inputs:
      query:
        value: select store_order_id,order_id,store_id,store_city,store_state from prod.reporting.store_orders_completed_core limit 10