resources:
  snowflake:
    config:
      secret_name: snowflake/analytics_api
      region: us-east-1
  redis:
    config:
      host: TODO
      port: 6379
      db: "0"
solids:
  get_because_you_bought_df:
    inputs:
      query:
        value: SELECT * FROM PROD.DATASCIENCE.{{cookiecutter.project_slug}}