resources:
  snowflake:
    config:
      secret_name: snowflake/analytics_api
      region: us-east-1
  redis:
    config:
      host: TODO
      port: 6379
      db: "0"
solids:
  get_{{cookiecutter.project_slug}}_df:
    inputs:
      query:
        value: SELECT key, value FROM PROD.DATASCIENCE.{{cookiecutter.project_slug}}